### ISSUE TITLE
use llvm how to set CmakeLists.txt

### ISSUE THREAD

**Issue by ebaecff** [Apress/beginning-cpp23#29]
I find article  https://www.kitware.com/import-std-in-cmake-3-30/ ,  but canot work

**Comment by gxglhyy** [comment]
here is example use llvm with Makefile, hope can help you.
https://gxglhyy.top/2024/10/28/Beginning-C++23.html

**Comment by ebaecff** [comment]
> here is example use llvm with Makefile, hope can help you. https://gxglhyy.top/2024/10/28/Beginning-C++23.html

感谢，有用。
