### ISSUE TITLE
Which compiler works for this?

### ISSUE THREAD

**Issue by sam-mix** [Apress/beginning-cpp23#5]
Which compiler works for this, I'm very interested in this.

**Comment by Peter-VanWeert** [comment]
Nearly all examples compiles with the latest Visual Studio preview version (https://visualstudio.microsoft.com/vs/preview/), provided you work around some unsupported features:
- `import std;`: write your own `std` module that adds `import export` for all relevant headers
- `std::print()` / `std::println()`: write your own `print` module that exports wrappers that forward to `std::format()` / `std::format_to()`
The WIP branch should have everything to get this to work, include CMake files to generate the Visual Studio projects.
